apiVersion: batch/v1
kind: Job
metadata:
  name: secret-fetch-job
spec:
  template:
    spec:
      containers:
      - name: secret-fetch-pod
        image: your-image:tag
      restartPolicy: Never
